# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d2cde644c2583348cedf208f005ee73bfdd6dab5d2f980dd08af86a1cd2c63b459225f174dba24c231ed524cfd16a02dfadcb85d2918da768d6de0b1f5318ab

test:
  secret_key_base: 4fd7253e896bdd864df4c5dc5173478569c665668633e2b1be581d0552597ad752d27d4db8a1e2b98599f9eccb89c5070ac56aa0516f07f456055da01fe43fb2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
